version: '3.3'
services:
  frontend:
    container_name: demo-todo-frontend
    build: ./frontend
    ports:
      - 8000:8000
    links:
      - backend
    environment:
      PORT: 8000
      API_URL: http://demo-todo-backend:8001

  backend:
    container_name: demo-todo-backend
    build: ./backend
    ports:
      - 8001:8001
    links:
      - mongo
    environment:
      MONGODB_URI: mongodb://didem:OvrjbKFBUhaed708oHcD@demo-todo-mongo:27017/?retryWrites=true&w=majority

  mongo:
    container_name: demo-todo-mongo
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - .pv/auth/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: didem
      MONGO_INITDB_ROOT_PASSWORD: OvrjbKFBUhaed708oHcD
